spring:
  docker:
    compose:
      lifecycle-management: start_only
  flyway:
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5444/tickets
    user: sumkin
    password: seminar4
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
custom:
  constants:
    regular-price: 30
    peak-hour-premium: 0.3
